# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-12 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Unknown')], default='u', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('u', 'Unknown')], max_length=10),
        ),
    ]
