# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-16 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0006_auto_20180316_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(default='s,m,l,xl', max_length=10),
        ),
    ]
